apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drivesale
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - adminer.yaml
